export const ADD_MESSAGE_ACTION = 'ADD_MESSAGE_ACTION';
export const GET_MESSAGE_ACTION = 'GET_MESSAGE_ACTION';
export const GET_MESSAGE_SUCCESS_ACTION = 'GET_MESSAGE_SUCCESS_ACTION';
export const GET_MESSAGE_FAILED_ACTION = 'GET_MESSAGE_FAILED_ACTION';
export const LOAD_MESSAGE_PENDING   = "LOAD_MESSAGE_PENDING";
export const LOAD_MESSAGE_SUCCESS   = "LOAD_MESSAGE_SUCCESS";
export const LOAD_MESSAGE_ERROR     = "LOAD_MESSAGE_ERROR";
export const LOG_USER               = "LOG_USER";





